[package]
name = "test-dynamo"
authors = ["Darwin Boersma <darwin@sadlark.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = {git = "https://github.com/fermyon/spin-rust-sdk"}
[workspace]
